### PR TITLE
Fix delay crash

### LINKED ISSUE #138: nrf5_sdk15 ri_flash_purge: Sometimes gets stuck in delay
Related issue #137 . A workaround is to use delay_us, but root cause of error should be found.

### LINKED ISSUE #139: Interface: Add a function to detect interrupt context

### PR DESCRIPTION
**Pull request by niksiboxi**
Fixing the crash issue on calling `ri_flash_purge();` function. Crash is due to the power management interrupt. Fixed by replacing `delay_ms` function with `delay_us`. Additionally added function to check the interrupt occurrence.
Resolves #138
Resolves #139

### CODE REVIEW

File: src/nrf5_sdk15_platform/flash/ruuvi_nrf5_sdk15_flash.c [hunk 1]
```diff
@@ -545,7 +546,16 @@ void ri_flash_purge (void)
     {
         int page = (FSTORAGE_SECTION_START / erase_unit) + p; // erase unit == virtual page size
         rc = sd_flash_page_erase (page);
-        ri_delay_ms (200);
+
+        if (ri_yield_is_interrupt_context)
```
Comment (ojousima) [inline src/nrf5_sdk15_platform/flash/ruuvi_nrf5_sdk15_flash.c:550]: This solves the issue only in this specific case, the proper fix is to check the interrupt context inside ri_delay_millis.
https://github.com/ruuvi/ruuvi.drivers.c/blob/1652e6abaada56d651d2d63424bc7b5e44662dc9/src/nrf5_sdk15_platform/yield/ruuvi_nrf5_sdk15_yield.c#L151

File: src/nrf5_sdk15_platform/yield/ruuvi_nrf5_sdk15_yield.c [hunk 2]
```diff
@@ -88,6 +88,13 @@ static void wakeup_handler (void * p_context)
     m_wakeup = true;
 }
 
+// Test if in interrupt mode
```
Comment (ojousima) [inline src/nrf5_sdk15_platform/yield/ruuvi_nrf5_sdk15_yield.c:91]: This comment could be removed, function better detailed in .h file.

**Review by ojousima — CHANGES_REQUESTED** [review]

File: src/nrf5_sdk15_platform/flash/ruuvi_nrf5_sdk15_flash.c (hunk 1 above)
Comment (niksiboxi) [reply src/nrf5_sdk15_platform/flash/ruuvi_nrf5_sdk15_flash.c]: Added check inside the `ri_delay_ms`

File: src/nrf5_sdk15_platform/yield/ruuvi_nrf5_sdk15_yield.c (hunk 2 above)
Comment (niksiboxi) [reply src/nrf5_sdk15_platform/yield/ruuvi_nrf5_sdk15_yield.c:91]: Removed

**Comment by DG12** [comment]
Adding a delay after flash does not seem like a good way to handle this.

**Comment by ojousima** [comment]
> Adding a delay after flash erase does not seem like a good way to handle this.

Are you referring to something in the latest code?

> Why even erase all flash anyway. If it is required just write 00000000 over record keys (no erase needed)

If application size has changed and flash area has shrunk, FDS cannot be initialized which means records cannot be updated. Also, writing zeros over some records would not free the space for other use

**Review by ojousima — APPROVED** [review]
Thanks, let's see what CI says

**Comment by DG12** [comment]
I am referring to ruuvi.drivers.c/src/nrf5_sdk15_platform/flashruuvi_nrf5_sdk15_flash.c
<pre>
for (int p = 0; (p < total_pages) && (NRF_SUCCESS == rc); p++)
    {
        int page = (FSTORAGE_SECTION_START / erase_unit) + p; // erase unit == virtual page size
        rc = sd_flash_page_erase (page);
        ri_delay_ms (200);
</pre>
With the default of 3 pages will delay .6seconds.

**Comment by ojousima** [comment]
```
/**@brief Flash Erase page
*
* Commands to erase a flash page
* If the SoftDevice is enabled:
*  This call initiates the flash access command, and its completion will be communicated to the
*  application with exactly one of the following events:
*      - @ref NRF_EVT_FLASH_OPERATION_SUCCESS - The command was successfully completed.
*      - @ref NRF_EVT_FLASH_OPERATION_ERROR   - The command could not be started.
*
* If the SoftDevice is not enabled no event will be generated, and this call will return @ref NRF_SUCCESS when the
* erase has been completed
*
* @note
*      - This call takes control over the radio and the CPU during flash erase and write to make sure that
*        they will not interfere with the flash access. This means that all interrupts will be blocked
*        for a predictable time (depending on the NVMC specification in the device's Product Specification
*        and the command parameters).
*      - This call will make the SoftDevice trigger a hardfault when the page is erased, if it is
*        protected.
*
*
* @param[in]  page_number           Page number of the page to erase
*
* @retval ::NRF_ERROR_INTERNAL      If a new session could not be opened due to an internal error.
* @retval ::NRF_ERROR_INVALID_ADDR  Tried to erase to a non existing flash page.
* @retval ::NRF_ERROR_BUSY          The previous command has not yet completed.
* @retval ::NRF_ERROR_FORBIDDEN     Tried to erase a page outside the application flash area.
* @retval ::NRF_SUCCESS             The command was accepted.
*/
SVCALL(SD_FLASH_PAGE_ERASE, uint32_t, sd_flash_page_erase(uint32_t page_number));
```

There's little benefit in writing code to determine if softdevice is enabled or not and catch the callback if yes for a function which is only called to erase all flash storage physically.

**Comment by DG12** [comment]
The delay after erase seems unnecessary.  Quoting the nRF52832 Product Specification v1.4

> 11.2 Erasing a page in Flash
> When erase is enabled, the Flash can be erased page by page using the ERASEPAGE register.
> After erasing a Flash page, all bits in the page are set to '1'. The time it takes to erase a page is specified by
> tERASEPAGE. The **CPU is halted** while the NVMC performs the erase operation..

Have you seen conclusive evidence that checking the busy flag can be tested by the CPU and indicate busy?
