### PR TITLE
Fix doxygen issues

### LINKED ISSUE #215: Doxygen errors
Check the doxygen check output for details

### PR DESCRIPTION
**Pull request by niksiboxi**
Resolve #215

### CODE REVIEW

**Comment by niksiboxi** [comment]
Failed issues requires new PR's inside `ruuvi.nrf_sdk15_3_overrides.c` projects:
- https://github.com/ruuvi/ruuvi.nrf_sdk15_3_overrides.c/blob/master/fds.h#L314
- https://github.com/ruuvi/ruuvi.nrf_sdk15_3_overrides.c/blob/master/t2t_lib/nfc_t2t_lib.h#L227

File: src/integration_tests/ruuvi_interface_gpio_interrupt_test.h [hunk 1]
```diff
@@ -21,17 +21,16 @@
 #define RI_GPIO_INTERRUPT_TEST_TABLE_SIZE 64
 
 /**
- * @brief Test GPIO interrupt initialization.
+ * @brief Test GPIO PWM initialization.
```
Comment (ojousima) [inline src/integration_tests/ruuvi_interface_gpio_interrupt_test.h:24]: Isn't this interrupt instead of PWM?

File: src/interfaces/log/ruuvi_interface_log.c [hunk 2]
```diff
@@ -346,16 +345,6 @@ void ri_log (const ri_log_severity_t severity,
     return;
 }
 
-/**
```
Comment (ojousima) [inline src/interfaces/log/ruuvi_interface_log.c:349]: Why this was removed?

File: src/tasks/ruuvi_task_adc.c [hunk 3]
```diff
@@ -421,4 +421,4 @@ rd_status_t rt_adc_ratiometric_sample (rd_sensor_configuration_t * const configu
     return err_code;
 }
 #endif
-/*@}*/
\ No newline at end of file
+/** @}*/
```
Comment (ojousima) [inline src/tasks/ruuvi_task_adc.c:424]: Add a newline

**Review by ojousima — CHANGES_REQUESTED** [review]

**Comment by ojousima** [comment]
Thanks, just some details to clean up

File: src/interfaces/log/ruuvi_interface_log.c (hunk 2 above)
Comment (niksiboxi) [reply src/interfaces/log/ruuvi_interface_log.c:349]: Incorrect issue previously fixed. Returned in latest commit.

File: src/integration_tests/ruuvi_interface_gpio_interrupt_test.h (hunk 1 above)
Comment (niksiboxi) [reply src/integration_tests/ruuvi_interface_gpio_interrupt_test.h:24]: Fixed in latest commit.
